### ISSUE TITLE
Implicações de uso de vm

### ISSUE THREAD

**Issue by farribeiro** [dinorox/warsawvm#1]
Olá!

Uma questão sobre o que você levantou sobre warsaw e vm, quais implicações se não estiver configurado os "contadores" da máquina hospedeira? Mesmo um projeto semelhante, em vagrant, não vi relatos de problemas de acesso.

Por gentileza, esclarecimentos.

**Comment by dinorox** [comment]
> Mesmo um projeto semelhante, em vagrant, não vi relatos de problemas de acesso.

Foi algo que me encucou tambem. E aparentemente todos os projetos funcionam sem problemas. Mas afetou o funcionamento do warsaw durante meus testes, lembro disso.

Testei agora sem passar as informacoes do host pro guest e funcionou normalmente. Ou seja, a parte de enganar o warsaw se tornou totalmente irrelevante.

Mas nao to maluco, gastei uma tarde inteira tentando entender por que o warsaw nao estava funfando e cheguei a conclusao apresentada aqui. Tanto eh que no `Como funciona` gastei a maioria do texto explicando como enganar o warsaw. Imagino que de la pra ca houve mudancas que removeram as restricoes de acesso via vm. O problema eh que nao da pra testar isso, entao a minha afirmacao nao vai passar de uma hipotese.

Enfim, vou atualizar a documentacao e o codigo.

Valeu!
